sudo: required
services:
  - docker
  
before_install:
  - docker build -t arun227/docker-fib -f ./client/Dockerfile.dev ./client
  
script:
  - docker run arun227/docker-fib npm test -- --coverage
  
after_success:
  - docker build -t arun227/multi-client ./client
  - docker build -t arun227/multi-nginx ./nginx
  - docker build -t arun227/multi-server ./server
  - docker build -t arun227/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push arun227/multi-client
  - docker push arun227/multi-nginx
  - docker push arun227/multi-server
  - docker push arun227/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-968814438247
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
  