sudo: required
services:
  - docker
  
before_install:
  - docker build -t docker-fib -f ./client/Dockerfile.dev ./client
  
script:
  - docker run docker-fib npm test -- --coverage
  
after_success:
  - docker build -t arun227/multi-client ./client
  - docker build -t arun227/multi-nginx ./nginx
  - docker build -t arun227/multi-server ./server
  - docker build -t arun227/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push arun227/multi-client
  - docker push arun227/multi-nginx
  - docker push arun227/multi-server
  - docker push arun227/multi-worker